name: check
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  check:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Check versions
        run: |
          deno --version
          npx jsr --version

      - run: deno fmt --check
      - run: deno lint
      - run: deno install
      - run: deno test
      - run: npx jsr publish --dry-run --allow-dirty
      - run: deno run example:job:hello
